# Move the directory to the second line
# format = "$directory$all$character$time"
format = """
$directory\
$git_branch\
$git_status\
ðŸ•’(fg:#394260) $time\
\n$character"""
right_format = """$time"""
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 2
# Inserts a blank line between shell prompts
add_newline = true
continuation_prompt = "â–¶â–¶"


[directory]
# style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# style = "bg:#33658A"
format = '$time'

[character] # The name of the module we are configuring is "character"
success_symbol = "[ðŸš€](bold green)" # The "success_symbol" segment is being set to "âžœ" with the color "bold green"